/*
 Generated by typeshare 1.11.0
*/

export enum MessageKind {
	User = "User",
	Assistant = "Assistant",
}

export interface Message {
	kind: MessageKind;
	content: string;
}

export enum Provider {
	OpenAI = "OpenAI",
	Ollama = "Ollama",
}

export interface Chat {
	id: string;
	name: string;
	messages: Message[];
	provider: Provider;
	model: string;
}

export interface OllamaRequest {
	model: string;
	prompt: string;
}

export interface OllamaResponse {
	response: string;
}

